validation:
  stable-matching:
    population:
      max: 3000
    generation:
      max: 1000
    individuals:
      min: 3
    run-count-per-algorithm:
      min: 5
      max: 25
  game-theory:
    population:
      max: 3000
    generation:
      max: 1000
    individuals:
      min: 3
    run-count-per-algorithm:
      min: 5
      max: 25
